server:
  port: 9994
spring:
  application:
    name: CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://gitee.
#          password:com/chao_happy/configs.git
#          username:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
